version: "3.8"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - OWNER_NAME=Ilham

  encryption-service:
    build: ./encryption-service
    ports:
      - "8082:8082"
    environment:
      - OWNER_NAME=Ilham